services:
  # Redis Cache (local container)
  redis:
    image: redis:7-alpine
    container_name: cars-bids-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - cars-bids-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6379:6379"
networks:
  cars-bids-network:
    driver: bridge

volumes:
  redis_data:
    driver: local