#!/bin/sh

# Docker start script for backend
echo "Starting Cars Bids Backend..."
echo "NODE_ENV: $NODE_ENV"
echo "PORT: $PORT"

# Check if critical environment variables are set
if [ -z "$DATABASE_URL" ]; then
    echo "ERROR: DATABASE_URL not set"
    exit 1
fi

if [ -z "$SESSION_SECRET" ]; then
    echo "ERROR: SESSION_SECRET not set"
    exit 1
fi

if [ -z "$JWT_SECRET" ]; then
    echo "ERROR: JWT_SECRET not set"
    exit 1
fi

if [ -z "$REDIS_URL" ]; then
    echo "ERROR: REDIS_URL not set"
    exit 1
fi

echo "Environment variables validated"

# Create .env files for dotenvx
echo "Creating environment files..."

# Create base .env file
cat > .env << EOF
# Base environment file
NODE_ENV=${NODE_ENV:-development}
EOF

# Create .env.production file with all variables
cat > .env.production << EOF
# Production environment for Docker
NODE_ENV=${NODE_ENV:-production}
PORT=${PORT:-5000}
API_URL=${API_URL}
DATABASE_URL=${DATABASE_URL}
DATABASE_PASSWORD=${DATABASE_PASSWORD}
SESSION_SECRET=${SESSION_SECRET}
JWT_SECRET=${JWT_SECRET}
REDIS_URL=${REDIS_URL}
CORS_ORIGIN=${CORS_ORIGIN}
CLIENT_URL=${CLIENT_URL}
FRONTEND_URL=${FRONTEND_URL}
STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
ENDPOINT_SECRET=${ENDPOINT_SECRET}
IMGBB_API_KEY=${IMGBB_API_KEY}
X_RAPID_API_KEY=${X_RAPID_API_KEY}
X_RAPID_API_HOST=${X_RAPID_API_HOST}
OPENAI_API_KEY=${OPENAI_API_KEY}
BREVO_API_KEY=${BREVO_API_KEY}
EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
EMAIL_FROM=${EMAIL_FROM}
SUPPORT_EMAIL=${SUPPORT_EMAIL}
SUPPORT_URL=${SUPPORT_URL}
BANK_NAME=${BANK_NAME}
BANK_ADDRESS=${BANK_ADDRESS}
BANK_ACCOUNT_NUMBER=${BANK_ACCOUNT_NUMBER}
BANK_IBAN=${BANK_IBAN}
BANK_SWIFT=${BANK_SWIFT}
ACCOUNT_HOLDER_NAME=${ACCOUNT_HOLDER_NAME}
OFFICE_ADDRESS=${OFFICE_ADDRESS}
WORKING_HOURS=${WORKING_HOURS}
PHONE_NUMBER=${PHONE_NUMBER}
PHONE_OPERATING_HOURS=${PHONE_OPERATING_HOURS}
SUPPORT_PHONE=${SUPPORT_PHONE}
SUPPORT_HOURS=${SUPPORT_HOURS}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_DASHBOARD_URL=${ADMIN_DASHBOARD_URL}
SUBSCRIPTION_SCHEDULER_ENABLED=${SUBSCRIPTION_SCHEDULER_ENABLED}
SUBSCRIPTION_FULL_SYNC_SCHEDULE=${SUBSCRIPTION_FULL_SYNC_SCHEDULE}
SUBSCRIPTION_PLAN_MONITOR_SCHEDULE=${SUBSCRIPTION_PLAN_MONITOR_SCHEDULE}
SUBSCRIPTION_ACTIVE_SYNC_SCHEDULE=${SUBSCRIPTION_ACTIVE_SYNC_SCHEDULE}
SECURE_COOKIES=${SECURE_COOKIES}
TZ=${TZ}
EOF

echo "Environment files created"
echo "Starting Node.js server..."

# Start the application with production environment
exec npm run start:prod
