/**
 * AI Car Analysis Service
 * Uses OpenAI Vision API to analyze car images and extract details
 */

import { loadApiConfig } from "../config/apiConfig";

const { apiUrl } = loadApiConfig();

export interface CarAnalysisResult {
  make?: string;
  model?: string;
  year?: string;
  color?: string;
  colorOriginal?: string;
  bodyType?: string;
  bodyTypeOriginal?: string;
  fuelType?: string;
  fuelTypeOriginal?: string;
  transmission?: string;
  transmissionOriginal?: string;
  condition?: string;
  estimatedPrice?: number;
  originalEstimatedPrice?: number;
  currency?: string;
  description?: string;
  sellingPoints?: string[]; // New field for key selling points
  confidence: number;
  mileageConsidered?: number;
  databaseValidation?: {
    makeExists: boolean;
    modelExists: boolean;
    needsManualReview: boolean;
  };
  // Enhanced fields generated by AI analysis
  generatedTitle?: string;
  enhancedDescription?: string; // Engine specifications
  hp?: number; // Horsepower
  engine_cylinders?: string; // Cylinder configuration (e.g., "I4", "V6", "V8")
  engine_liters?: number; // Engine displacement in liters
}

export interface AIAnalysisResponse {
  success: boolean;
  data?: CarAnalysisResult;
  error?: string;
  warnings?: string[];
}

/**
 * Analyze car image using AI
 */
export const analyzeCarImage = async (
  imageFile: File,
  mileage?: number
): Promise<AIAnalysisResponse> => {
  try {
    const formData = new FormData();
    formData.append("image", imageFile);

    if (mileage) {
      formData.append("mileage", mileage.toString());
    }

    const response = await fetch(`${apiUrl}/ai/analyze-car`, {
      method: "POST",
      credentials: "include",
      body: formData,
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        errorData.error || `Analysis failed: ${response.statusText}`
      );
    }

    const result = await response.json();
    return result;
  } catch (error) {
    console.error("Error analyzing car image:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error occurred",
    };
  }
};

/**
 * Get supported image formats for car analysis
 */
export const getSupportedImageFormats = (): string[] => {
  return ["image/jpeg", "image/jpg", "image/png", "image/webp"];
};

/**
 * Validate image file for analysis
 */
export const validateImageFile = (
  file: File
): { valid: boolean; error?: string } => {
  const maxSize = 10 * 1024 * 1024; // 10MB
  const supportedFormats = getSupportedImageFormats();

  if (!supportedFormats.includes(file.type)) {
    return {
      valid: false,
      error: "نوع الملف غير مدعوم. يرجى استخدام JPG, PNG, أو WebP",
    };
  }

  if (file.size > maxSize) {
    return {
      valid: false,
      error: "حجم الملف كبير جداً. الحد الأقصى 10 ميجابايت",
    };
  }

  return { valid: true };
};
